#Config
spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
spring.resources.add-mappings=true
spring.resources.static-locations=classpath:/resources/
server.servlet.contextPath=/gladius
server.port=8185
app.version=@project.version@

#Despliegue AWS Elastic Beanstalk<46
spring.datasource.url=jdbc:postgresql://ec2-18-227-209-19.us-east-2.compute.amazonaws.com:5432/gladius05
spring.datasource.username=postgres
spring.datasource.password=@balkaned2020

#Despliegue Local Tomcat 9
#spring.datasource.url=jdbc:postgresql://localhost:5432/gladius05?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#spring.datasource.username=postgresql
#spring.datasource.password=postgres

#Multipart
spring.servlet.multipart.max-file-size=40MB
spring.servlet.multipart.max-request-size=50MB

#spring.datasource.url = ${sqlURL}

