#Config
spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
spring.resources.add-mappings=true
spring.resources.static-locations=classpath:/resources/
server.servlet.contextPath=/gladius
server.port=8080
app.version=@project.version@

#Conexion BD AWS
spring.datasource.url=jdbc:postgresql://ec2-18-227-209-19.us-east-2.compute.amazonaws.com:5432/gladius05
spring.datasource.username=postgres

#spring.datasource.password=9huy75Ko9J5owzdTwXdh4Zw6UhZBRyvCJVTFoSkvjwYRnImSnw/tCMoKaHprAbHE
spring.datasource.password=ENC(9huy75Ko9J5owzdTwXdh4Zw6UhZBRyvCJVTFoSkvjwYRnImSnw/tCMoKaHprAbHE)
jasypt.encryptor.password=@balkaned2020
#jasypt.encryptor.password=9huy75Ko9J5owzdTwXdh4Zw6UhZBRyvCJVTFoSkvjwYRnImSnw/tCMoKaHprAbHE

#Despliegue Local Tomcat 9
#spring.datasource.url=jdbc:postgresql://localhost:5432/gladius05?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#spring.datasource.username=postgresql
#spring.datasource.password=postgres

#Multipart
spring.servlet.multipart.max-file-size=400MB
spring.servlet.multipart.max-request-size=500MB

#spring.datasource.url = ${sqlURL}

