package com.balkaned.gladius.beans;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Empleado {

    Integer iexcodcia ;
    Integer iexcodtra ;
    String iexnomtra ;
    String iexapepat ;
    String iexapemat ;
    String iextipdocid ;
    String iexnrodoc ;
    String iexfecnac ;
    String iexfecing ;
    String iextipcese ;
    String iexfecret ;
    String iexcodsex ;
    String iexpaisemisor ;
    String iexflgest ;
    String iexcodant ;
    String iextiptra ;
    String iexmodform ;
    String iexnacion_origen ;
    String iexdepart_origen ;
    String iexprovin_origen ;
    String iexdistri_origen ;
    String iexcentroform ;
    String iexflgdomicil ;
    String iexsituapen ;
    String iextipcont ;
    String iexfecini_cont;
    String iexfecfin_cont ;
    String iexpliego ;
    String iexsituaesp ;
    String iexocupacion_pub;
    String iexocupacion_priv ;
    String iexpuesto ;
    String iexccosto ;
    String iexarea ;
    String iexubilocal ;
    String iexcateg_trabajador ;
    String iexreglab ;
    String iexcodafp ;
    String iexfecafp ;
    String iexcussp ;
    String iextippago;
    String iexperrem ;
    String iexcodban_hab;
    String iexflgbancci_hab ;
    String iexcodmon_hab ;
    String iextipban_hab ;
    String iexnrocta_hab ;
    String iexcodban_cts ;
    String iexflgbancci_cts ;
    String iexcodmon_cts;
    String iextipban_cts;
    String iexnrocta_cts;
    String iexessalud ;
    String iexsenati ;
    String iexflgeps ;
    String iexcodeps ;
    String iexconvdobtrib ;
    String iexcodlardist ;
    String iexnrotelf ;
    String iexemail ;
    String iexemail_coorp ;
    String iextipvia_dom1 ;
    String iexnomvia_dom1;
    String iexnrovia_dom1 ;
    String iexdeptin_dom1;
    String iexinterior_dom1 ;
    String iexmanzana_dom1;
    String iexlote_dom1 ;
    String iexkilometro_dom1 ;
    String iexblock_dom1 ;
    String iexetapa_dom1 ;
    String iextipzona_dom1 ;
    String iexnomzona_dom1 ;
    String iexreferencia_dom1 ;
    String iexubigeo_dom1 ;
    String iextipvia_dom2 ;
    String iexnomvia_dom2 ;
    String iexnrovia_dom2 ;
    String iexdeptin_dom2 ;
    String iexinterior_dom2 ;
    String iexmanzana_dom2 ;
    String iexlote_dom2;
    String iexkilometro_dom2 ;
    String iexblock_dom2;
    String iexetapa_dom2;
    String iextipzona_dom2;
    String iexnomzona_dom2;
    String iexreferencia_dom2 ;
    String iexubigeo_dom2 ;
    String iexflgdomicilio;
    String iexdiscapacidad ;
    String iexsctrpension ;
    String iexregalter ;
    String iexjornmax ;
    String iexhornocturno ;
    String iexsindicalizado;
    Double iexmontorem ;
    String iexexon5ta ;
    String iexnroruc_cas ;
    String iexmadreresp ;
    String iextipocentoedu ;
    String iexfeccrea ;
    String iexfeccmod ;
    String iexusucrea ;
    String iexusumod ;
    String destipcese;
    String dessex;
    String despaisemisor;
    String desestado;
    String destiptra;
    String desmodform;
    String desnacion_origen;
    String desdepart_origen;
    String desprovin_origen;
    String desdistri_origen;
    String iexflgcomi_mix;
    String iexctlasipag ;
    String despuesto;
    String desccosto;
    String desarea;
    String desubicacion;
    String iexgrdinstruccion;
    String desinstruccion;
    String descentroform;
    String iexflgjubil;
    String iexflgmas_vida;
    String feciniing_par;
    String fecfining_par;
    String txtfinder;
    String iexlogo;
    String iexestcivil;
    String iextipturno;
    String iexlunes;
    String iexmartes;
    String iexmiercoles;
    String iexjueves;
    String iexviernes;
    String iexsabado;
    String iexdomingo;
    Integer iexturlun;
    Integer iexturmar;
    Integer iexturmie;
    Integer iexturjue;
    Integer iexturvie;
    Integer iextursab;
    Integer iexturdom;
    String rango_sueldo ;
    String rango_edad ;
    String anio_ing;
    Integer headcount;
    String iexusumodlab;
    String iexfecmodlab;
    String iexusumoddom;
    String iexfecmoddom;
    String iexusumodseg;
    String iexfecmodseg;
    String iexusumodpag;
    String iexfecmodpag;
    String iexnacion_origen1;
    String iexdepart_origen1;
    String iexprovin_origen1;
    String iexnacion_origen2;
    String iexdepart_origen2;
    String iexprovin_origen2;
    String direccion1;
    String direccion2;
    String letraIni;
    String nomCompactoUpper;

}
